### ISSUE TITLE
Add support for multiple accounts

### ISSUE THREAD

**Issue by ndodger** [gabbersepp/ib-flex-reader#31]
If more than one account is included in the FlexQuery, there will be multiple <FlexStatement> tags under <FlexStatement**s**>.  The FlexStatements class can support this by making the FlexStatement property a List<>.

```
public class FlexStatements
    {
          public List<FlexStatement> FlexStatement { get; set; }
          public int? Count { get; set; }
    }
```

**Comment by gabbersepp** [comment]
Hi, I will try this.

**Comment by ndodger** [comment]
Hi Josef,

I appreciate the work you put into this IbFlexReader.  I am working on adding support for several more sections of the FlexStatement.  Would you like me to contribute those somehow?

Cheers,
Dan

**Comment by gabbersepp** [comment]
Feel free to make a pull request :-) this would be great :)

ndodger <notifications@github.com> schrieb am Do., 9. Juli 2020, 14:38:

**Comment by ndodger** [comment]
I have added support for several more report sections.  However, IB is notorious for putting odd filler characters in report fields.  Sometimes dates or prices will have a single hyphen.   Here are some examples from an actual IB generated file:
openCloseIndicator="-"
multiplier="-"
value="-"
closePrice="-"

Unfortunately these values are incompatible with certain class properties.  The problem arises with the properties defined as DateTime or as an enum like OpenCloseIndicator.  Changing those properties to string breaks the code in Logic.SplitUpOpenCloseTrades() as well as many of the existing tests.

Do you have a suggestion for handling these cases so that it doesn’t break your existing code or tests?

Thanks,
Dan

**Comment by gabbersepp** [comment]
@ndodger  sorry for the late response. 
A quick and dirty solution would be to replace all occurences of "-" with an empty string. But this is a bit hacky I think. Maybe an alternative solution is to write an own deserializer. But I am not sure if this solution is a bit too much for this problem.

**Comment by ndodger** [comment]
No worries on the late response.

I made a pull request with a lot of additions and a few changes.  But it looks like I broke Travis CI because my .csproj files were referencing a local EnumParser project. (Sorry, I should have realized that would be a problem.)  I have corrected this in my branch and can submit another pull request but I will wait to hear from you before doing anything further.

**Comment by ndodger** [comment]
Completed.
